---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
knitr::opts_chunk$set(warnings = FALSE, message = FALSE)
```

[Catalan Elections] The `Catalan_elections` dataset contains data on eleven elections in a region of Spain; in each election, the percentage of voters in each of 949 municipalities voting for "Indy" or for "Unionist" are tracked.

```{r}
library(tidyverse)
library(ggridges)
library(ggbeeswarm)
Catalan_elections
```

a. Use a geom from `ggplot2` to visualize: In each of the 11 elections in the dataset, what was the distribution of % voters for Indy in each municipality?

```{r}
Catalan_elections %>% 
  filter(Option == "Indy") %>% 

ggplot(aes(x = Percent/100, y = as.factor(Year))) +
  geom_boxplot() +
  scale_x_continuous(labels = scales::label_percent()) +
  labs(
    x = "",
    y = "",
    title = "Distribution of Indy Voters in Municipalities"
  ) +
  theme_classic() +
  theme(
    panel.grid.major.y = element_line() 
  ) +
  geom_vline(xintercept = 0.5, linetype = "dashed")
```

b. Use either `geom_density_ridges` from `ggridges` or `geom_beeswarm` from `ggbeeswarm` to answer the same question.

```{r}
Catalan_elections %>% 
  filter(Option == "Indy") %>% 

ggplot(aes(x = Percent/100, y = as.factor(Year))) +
  geom_density_ridges() +
  scale_x_continuous(labels = scales::label_percent(),
                     breaks = c(0, .25, .5, .75, 1),
                     limits = c(0, 1)) +
  labs(
    x = "",
    y = "",
    title = "Distribution of Indy Voters in Municipalities"
  ) +
  theme_classic() +
  theme(
    panel.grid.major.y = element_line() 
  ) +
  geom_vline(xintercept = 0.5, linetype = "dashed")
```

```{r}
Catalan_elections %>% 
  filter(Option == "Indy") %>% 

ggplot(aes(x = Percent/100, y = as.factor(Year))) +
  geom_beeswarm(alpha = 0.1) +
  scale_x_continuous(labels = scales::label_percent(),
                     breaks = c(0, .25, .5, .75, 1),
                     limits = c(0, 1)) +
  labs(
    x = "",
    y = "",
    title = "Distribution of Indy Voters in Municipalities"
  ) +
  theme_classic() +
  theme(
    panel.grid.major.y = element_line() 
  ) +
  geom_vline(xintercept = 0.5, linetype = "dashed")
```

c. Why did you choose the `geom` you did in part b? How does it improve on the plot from part a?
