---
title: "Untitled"
output: html_document
date: "`r Sys.Date()`"
---

```{r}
knitr::opts_chunk$set(warnings = FALSE, message = FALSE)
th <- theme_classic() +
    theme(
        axis.text = element_text(size = 14),
        legend.text = element_text(size = 14),
        axis.title = element_text(size = 20),
        legend.title = element_text(size = 20),
        strip.text = element_text(size = 20)
    )
theme_set(th)
```


[Plant Growth Experiment] This problem will give you practice with tidying a dataset so that it can be easily visualized. The data describe the height of several plants measured every 7 days. The plants have been treated with different amounts of a growth stimulant. The first few rows are printed below -- `height.x` denotes the height of the plant on day `x`.

```{r}
library(tidyverse)
plants <- read_csv("https://uwmadison.box.com/shared/static/qg9gwk2ldjdtcmmmiropcunf34ddonya.csv")
plants
```

a. Propose an alternative arrangement of rows and columns that conforms to the tidy data principle.

b. Implement your proposed arrangement from part (a).

```{r}
plants_tidy = plants %>% 
  pivot_longer(c("height.0", "height.7", "height.14", "height.21"),
               names_to = "time", values_to = "height") %>% 
  mutate(
    time = str_remove(time, "height.")
    #time = str_extract(time, "[0-9]+$")
  )
```

c. Using the dataset from (b), design and implement a visualization showing the growth of the plants over time according to different treatments.

```{r}
ggplot(plants_tidy, aes(as.numeric(time), height, col = treatment)) +
  geom_line() +
  facet_wrap(~plantid)
```

```{r}
ggplot(plants_tidy, aes(as.numeric(time), height, group = interaction(plantid, treatment))) +
  geom_line()
```

